### ISSUE TITLE
Deployment failed 😢 

### ISSUE THREAD

**Issue by zuevval** [braille-systems/learnbraille_ios#200]
Запуск в TestFlight (а также в Google Play) [упал](https://github.com/braille-systems/learnbraille_ios/actions/runs/1268508314)

Что с GooglePlay, я примерно понял по логам: с августа новым приложениям нельзя указывать целевой API ниже 30. Думаю, несложно будет исправить.

<img width=350 alt="Google Play console screenshot" src=https://user-images.githubusercontent.com/23435506/134621335-3ad06ec3-f263-4975-ac1d-1d9cc8926039.png>

Что с iOS, честно говоря, пока не понял. @ThinkingFrog не мог бы ты посмотреть, пожалуйста? 

Итак, нужно исправить
- [x] Deployment to GooglePlay
- [x] Deployment to TestFlight

**Comment by ThinkingFrog** [comment]
С тестфлайтом тоже самое, указана слишком низкая минимальная версия оси. Можно попробовать перевести всё на флаттер 1 и посмотреть, не пофиксится ли само. Либо поднимать минимальную ОС, сейчас кажется 8 стоит

**Comment by zuevval** [comment]
Попробую посмотреть, спасибо. С GooglePlay откат до Flutter 1 точно не поможет.

**Comment by ThinkingFrog** [comment]
Кажется, что из-за перехода флаттера на вторую версию возникает слишком много проблем. Надо либо перевозить проект на flutter 2.5 (последнюю актуальную) и фиксить, что сломается, либо везде в сиае проставлять flutter 1.x и продолжать работать как есть. Но я не знаю, как долго первая версия флаттера будет поддерживаться. В любом случае надо зафиксировать какую-то конкретную версию, иначе проблемы будут возникать регулярно

**Comment by zuevval** [comment]
@ThinkingFrog у меня тут [новая проблема](https://github.com/braille-systems/learnbraille_ios/runs/3709033310) с GooglePlay: не могу понять, как инкрементировать номер версии. Попробовал поднять версию приложения с 0.6.0 до 0.6.1, но не помогло. Как вы это делали раньше?

**Comment by zuevval** [comment]
По поводу флаттера: в сборке сейчас вроде стоит 2.5.1. Пожалуй, его и зафиксирую в `pubspec.yaml`

**Comment by ThinkingFrog** [comment]
Версию флаттера надо тогда во всех джобах одну делать. Сборка под 2.5, а линтер и деплой под 1 это странно. Тем более в деплое пересборка с сертификатами происходит и в итоге деплоится проект с 1 версии

**Comment by ThinkingFrog** [comment]
Для гугл плея важны номера сборки, если они не инкрементируются, то будут проблемы с деплоем

**Comment by zuevval** [comment]
> Для гугл плея важны номера сборки, если они не инкрементируются, то будут проблемы с деплоем

Можешь, пожалуйста, сказать, где их найти? В файлах проекта? В secrets? Где-то ещё?

**Comment by zuevval** [comment]
Между прочим, в августе GitHub Actions анонсировали [композицию workflow](https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/). Попробую заодно это использовать для уменьшения дупликации между `deployment` и `development`

**Comment by zuevval** [comment]
UPD: вроде deployment удалось перевести на 2.5.1

**Comment by ThinkingFrog** [comment]
> > Для гугл плея важны номера сборки, если они не инкрементируются, то будут проблемы с деплоем
> 
> @ThinkingFrog можешь, пожалуйста, сказать, где их найти? В файлах проекта? В secrets? Где-то ещё?

В номере версии после + идёт

**Comment by ThinkingFrog** [comment]
> Между прочим, в августе GitHub Actions анонсировали [композицию workflow](https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/). Попробую заодно это использовать для уменьшения дупликации между `deployment` и `development`

Прикольно, завозят наконец фичи из гитлаба. Тоже гляну в ближайшие дни

**Comment by zuevval** [comment]
в общем, я почитал про composite actions - это, конечно, здорово, но надо создавать отдельный репозиторий для хранения переиспользуемых YAML'ов. Полагаю, это заслуживает отдельной задачи, пока оставим как есть.
