### ISSUE TITLE
Ошибка в справке

### ISSUE THREAD

**Issue by zuevval** [braille-systems/learnbraille_ios#209]
После того, как я изменил справку в главном меню, справка при просмотре символа падает с ошибкой

<img width=250 src=https://user-images.githubusercontent.com/23435506/135708670-30d42a40-430b-4dca-91e6-efd9f8f9cee1.png>

**Comment by ThinkingFrog** [comment]
Такая ошибка уже была, кажется связана с тем, что в массиве элементов меню индекс вылетает за границы. Кажется я даже на это юнит-тесты писал, странно, что не свалились

**Comment by zuevval** [comment]
В любом случае, я виниват, что не посмотрел, но там вроде очень просто исправить, в ближайшее же время сделаю, как руки дойдут. Надеюсь, это последнее, что понадобится сделать перед выпуском
