### ISSUE TITLE
Странные png файлы в /docs

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learnbraille_ios#40]
Могу просматривать их только в гитхабе. Локально их не открывает даже GIMP.

**Comment by ThinkingFrog** [comment]
Они в lfs лежат, скорее всего у тебя просто не подтягиваются. У меня и в гимпе, и в вскоде всё открывается

**Comment by winter-yuki** [comment]
Правда, у меня пакета в системе не было, спасибо!
