### ISSUE TITLE
/data/Help.xml это не utf-8

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learnbraille_ios#41]
![unicode](https://user-images.githubusercontent.com/25281147/110792811-e8534f80-8284-11eb-8d01-125ef8219e5b.png)

**Comment by ThinkingFrog** [comment]
@derkanw Да, надо поменять кодировку в заголовке, с этим могут быть проблемы. Вчера ещё заметил, но забыл сказать

**Comment by winter-yuki** [comment]
Может лучше кодировку документа поменять? Куда без utf-8.

**Comment by ThinkingFrog** [comment]
Русский текст в utf-8 не закодируется, а как и для кого делать справку на английском не очень понятно. Может стоит поменять кодировку не на cp1251, а на какую-то другую, которая точно воспримется телефонами, но я слабо представляю, как оставить этот документ в utf-8

**Comment by winter-yuki** [comment]
Так, подожди. Ты utf ни с чем не путаешь? Это расширяющаяся юникодная кодировка, которая и тортики поддерживает, не то что кириллицу https://habr.com/ru/post/135913/

**Comment by ThinkingFrog** [comment]
Да, что-то меня поломало. Перекодировал в utf-8 с помощью enconv, сейчас залью пулл реквестом

**Comment by ThinkingFrog** [comment]
#53

**Comment by winter-yuki** [comment]
Done
