### ISSUE TITLE
Platform-specific code

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learnbraille_ios#42]
В корневой директории видно директории, соответствующие каждой из платформ, поэтому ожидается, что в `/lib` лежит common code для каждой из них.

Но например ![тут](https://github.com/braille-systems/learnbraille_ios/blob/3c08eaa3b75eb83a3bdaf0cebf7776625d53999e/braille_abc/lib/style.dart) обращение в купертино не выглядит общим для платформ. Даже если это соберётся везде, это странно.
```dart
import 'package:flutter/cupertino.dart';
// ...
color: CupertinoColors.separator,
```

**Comment by ThinkingFrog** [comment]
У нас в CI стоит обязательная сборка под андроид, без неё реквест не проходит в мастер. И я периодически ставлю себе на телефон апкшник, пока всё работает. Насколько я помню, проблема была в том, что без купертино это не заведётся именно на айфонах, но лучше узнать у @pikabol88 и @OvechkinDanil

**Comment by OvechkinDanil** [comment]
Мы импортировали cupertino, так как в нём содержатся виджеты с интерфейсами, которые является стандартом для приложений под IOS.
Если я правильно понял вопрос.

**Comment by winter-yuki** [comment]
Если представить, что это приложение для всех платформ, то логично было бы, если все обращения к платформенному API были в соответствующих директориях (`import 'package:flutter/cupertino.dart';` в файлах только в `/ios`, и т.д.).

Но тут тогда не очень понятно. Если у нас UI один на все платформы, то как брать нужные цвета, например? То есть нам в один и тот же экран надо взять либо цвет из купертино, либо цвет из андроида. Не должен же такой код брать и работать в андроиде как ни в чем ни бывало?
```
import 'package:flutter/cupertino.dart';
// ...
color: CupertinoColors.separator,
```

Понятно, что вы только под IOS делаете, но понимание таких вещей ~= пониманию платформы.

**Comment by pikabol88** [comment]
Все виджеты Купертино и виджеты Материал дизайна построены с использованием одной и той же базовой структуры.  Flutter создает весь пользовательский интерфейс с помощью движка Skia. 
То, какой пакет виджетов мы используем, влияет только на внешний вид виджетов.
Что касается CupertinoColors.separator, так это просто константа с кодом цвета

Поэтому да, такой код без проблем работает на андроид

**Comment by winter-yuki** [comment]
Понятно, спасибо!
