### ISSUE TITLE
Литералы

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learnbraille_ios#43]
В коде везде захардкожены числовые и строковые литералы. Android SDK предоставляет механизм, который позволяет задать надписи для разных языков, а размеры для разных экранов, и сам подставляет нужные на каждом устройстве. Думаю, с flutter примерно так же. Потом будет сложно семантически группировать разбросанные по коду константы.

То же самое с цветами и стилями.

**Comment by ThinkingFrog** [comment]
Вроде были проблемы с растягиванием на разных экранах, но я не помню, решились они или нет. В любом случае вопрос к @pikabol88 @OvechkinDanil и возможно @Oleg595 о том, как во флаттере принято работать с литералами

**Comment by pikabol88** [comment]
Сложно сказать, что «принято во флаттер»
Создаётся такое чувство, что ещё особо ничего и не принято...

С константами пока разбираемся.
Написано несколько функций, которые в зависимости от константы, возвращали бы размер процентном соотношении и тогда бы не было проблем с различным внешним видом на разных устройствах, но пока это не совсем работает.

Попытки найти пакеты, которые бы хоть как-то автоматизировали этот процесс пока тоже безуспешны.

Поэтому данный issue очень даже актуален

**Comment by ThinkingFrog** [comment]
Стили сгруппировали, кажется, что стало лучше. @pikabol88 можем закрывать?

**Comment by pikabol88** [comment]
> Стили сгруппировали, кажется, что стало лучше. @pikabol88 можем закрывать?

Стили вынесли, но с размерами так и не разобрались. Но и решили, что пока это всё-таки оставим, тк не удалось найти какие-либо средства flutter для абстрагирования от размерных констант
