### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learnbraille_ios#44]
Возникает впечатление, что ревью кода у вас не работает. Конечно формально без двух ревью слить нельзя, но кажется что это только формальность. Процессы должны помогать разработка, а не стоять в стороне или мешать ей, мы не в банке работаем.

Например, ![тут](https://github.com/braille-systems/learnbraille_ios/blob/3c08eaa3b75eb83a3bdaf0cebf7776625d53999e/braille_abc/lib/symbol/image_symbol.dart#L9) автор в комментарии переводит имя поля. Если бы механизм ревью работал, это бы точно не прошло.

**Comment by ThinkingFrog** [comment]
Я готов бесконечно плюсовать эту тему. Апрувы обычно ставятся вслепую, смысла в таких ревью нет никакого, хоть в сто апрувов лимит ставь, меня это сильно раздражает. 

Периодически стараюсь сам что-то смотреть, но у меня меньше опыта и с флаттером, и конкретно с этой кодовой базой. И рук на все реквесты не хватает. Ревью нужно проводить всей командой разработки (как минимум @pikabol88 @OvechkinDanil @Oleg595 ), это делает лучше и код, и всех участников ревью как людей и программистов.

Как решение этой проблемы, можно на планировании определять двух или хотя бы одного обязательных ревьюверов на каждую задачу. Это в том числе связано с тем, что ни у кого из участников проекта нет опыта проведения код ревью, но если не начинать, то он и не появится.

Проблему нужно решать, либо на личном уровне (большее участие каждого из членов команды), либо на уровне команды (назначать принудительно ревьюверов)

**Comment by winter-yuki** [comment]
Можете иногда ревью на меня кидать с кем-нибудь в пару. Времени на тестирование и вчитывание у меня не будет, но code smell могу быстро отметить хотя бы.

**Comment by zuevval** [comment]
Может, подключить в CI CodeFactor? Или SonarCloud, [как у Павла Олеговича в miew](https://github.com/epam/miew)

**Comment by ThinkingFrog** [comment]
@zuevval посмотрю, спасибо за наводку

**Comment by zuevval** [comment]
Гм, я думал, он найдёт больше issues: [![CodeFactor](https://www.codefactor.io/repository/github/braille-systems/learnbraille_ios/badge)](https://www.codefactor.io/repository/github/braille-systems/learnbraille_ios)

Может быть, поддержка Dart, введённая в codefactor в январе 2021, пока не очень продвинутая.

**Comment by ThinkingFrog** [comment]
@zuevval Да, я тоже посмотрел, он почти не поддерживает dart. Те ошибки, которые находит, в основном отступы в ямле и ещё какой-то kt-файл. SonarQube не поддерживает dart в принципе

**Comment by ThinkingFrog** [comment]
Ревью начали проводить активнее, плюс добавили улучшенный статический анализатор. Кажется, что можно закрывать
