### ISSUE TITLE
Комментарии

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learnbraille_ios#45]
Вы явно злоупотребляете комментариями. Обычно комментарий - это символ провала:
- программиста, который не придумал простого решения, которое не нужно объяснять
- программиста, который не смог написать выразительный код, а код почти всегда должно быть проще читать, чем прозу
- создателя языка, в котором (языке) что-то нельзя выразить нормально.

Документация - другое дело, но вы не java common enterprize organizations super serious legal protected API пишете.

**Comment by ThinkingFrog** [comment]
Комментариев стало меньше, код стал читабельнее. В целом, всё учтено, считаю, что можно закрывать
