### ISSUE TITLE
Язык

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learnbraille_ios#46]
Окей если вы на гитхабе между собой по-русски общаетесь, мб кому-то сложно. Но по-русски комментарии писать это совсем странно. Если очень тяжело автору, то лучше договориться и с ревьюером на пару написать нормальные англоязычные комменты. Или не писать #45.

**Comment by ThinkingFrog** [comment]
Комментариев в целом стало меньше, а те, что есть, пишутся на английском. Общение в пулл реквестах ещё на русском, но вряд ли имеет смысл это менять. Считаю, что можно закрыть
