### ISSUE TITLE
Optional arguments

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learnbraille_ios#47]
Насколько я понимаю, в фигурных скобках пишутся опциональные именованные аргументы у функций. Но почему этого так много в коде, опциональных аргументов без дефолтных значений? Например, ![тут](https://github.com/braille-systems/learnbraille_ios/blob/3c08eaa3b75eb83a3bdaf0cebf7776625d53999e/braille_abc/lib/symbol/image_symbol.dart#L27).

**Comment by ThinkingFrog** [comment]
@pikabol88 @OvechkinDanil @Oleg595 парируйте, либо закладываем тоже на рефакторинг

**Comment by winter-yuki** [comment]
> Насколько я понимаю, в фигурных скобках пишутся опциональные именованные аргументы у функций. Но почему этого так много в коде, опциональных аргументов без дефолтных значений? Например, ![тут](https://github.com/braille-systems/learnbraille_ios/blob/3c08eaa3b75eb83a3bdaf0cebf7776625d53999e/braille_abc/lib/symbol/image_symbol.dart#L27).

Пример не валиден, потому что там `@required` и тогда это обязательные именованные аргументы, но всё равно в коде досаточно примеров, когда `required` забыли.

**Comment by winter-yuki** [comment]
И вроде в новых версиях дарта это уже ключевое слово и можно писать без собаки.

**Comment by winter-yuki** [comment]
И ещё много случаев, когда в именованных аргументах смысла нет а достаточно позиционных, например ![тут](https://github.com/braille-systems/learnbraille_ios/blob/0c7af389a5a71d93462c924ce742cf518c1bb543/braille_abc/lib/symbol/struct_symbol.dart#L69).

Именованные нужны в основном тогда, когда на call site не понятно, что за параметры передаются, например
```
doSmth(true, true, false, 5, 4, 42);
```

**Comment by winter-yuki** [comment]
Также именованные аргументы часто используют для маскирования антипаттерна "телескопический конструктор", когда у него слишком много аргументов, класс, скорее всего, слишком много на себя берёт (если это не DI).

**Comment by ThinkingFrog** [comment]
На прошлой неделе выяснили, что фигурные скобки это не опциональные аргументы, а синтаксис флаттера. С этим сделать ничего не можем, тему закрываю
