### ISSUE TITLE
Декомпозиция в UI

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learnbraille_ios#48]
Не смотря на то, что flutter предоставляет хороший DSL для интерфейсов, мне кажется, надо не забывать о его декомпозиции. Код с таким уровнем вложенности как ![тут](https://github.com/braille-systems/learnbraille_ios/blob/3c08eaa3b75eb83a3bdaf0cebf7776625d53999e/braille_abc/lib/screens/letter_screen.dart#L67) довольно сложно читать.

**Comment by ThinkingFrog** [comment]
Тоже задача для рефакторинга. Надо наверное сделать новую объединяющую issue под это дело и линкануть в неё уже существующие

**Comment by ThinkingFrog** [comment]
Кажется, что вложенности стало меньше. По крайней мере пулл реквесты читать стало проще. @pikabol88 можно закрывать?

**Comment by pikabol88** [comment]
> Кажется, что вложенности стало меньше. По крайней мере пулл реквесты читать стало проще. @pikabol88 можно закрывать?

Да, думаю можем
