### ISSUE TITLE
Структура проекта

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learnbraille_ios#49]
В `/lib` вместе лежат куски UI (экраны, компоненты и проч), утилиты (shared) и данные (symbol). Неплохо было бы иметь более строгую структуру проекта. Например, у нас сделано в андроиде ![так](https://github.com/braille-systems/learn-braille/tree/master/app/src/main/java/com/github/braillesystems/learnbraille).

**Comment by ThinkingFrog** [comment]
Меня это тоже в начале смутило, но вроде это стиль у флаттера такой, хранить все исходники в куче в lib. Думаю, @pikabol88 сможет больше рассказать

**Comment by pikabol88** [comment]
Да, если посмотреть проект, который flutter предоставляет как демо, то там main уже лежит в lib.
Я тоже нахожу это слегка странным, но проанализировав несколько проектов на flutter, могу сказать, что структура везде примерно одна. 
lib всегда содержит что-то похожее на screens, components и models (в названиях возможны разные извращения)
