### ISSUE TITLE
Иммутабельность

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learnbraille_ios#50]
Всё в коде по умолчанию должно быть `final`. Если это не так, это странно (если не тривиальный случай индекса в цикле).

Например, не видно сходу никаких причин не сделать ![этот](https://github.com/braille-systems/learnbraille_ios/blob/3c08eaa3b75eb83a3bdaf0cebf7776625d53999e/braille_abc/lib/symbol/image_symbol.dart#L7) класс иммутабельным. И ![этот](https://github.com/braille-systems/learnbraille_ios/blob/3c08eaa3b75eb83a3bdaf0cebf7776625d53999e/braille_abc/lib/symbol/struct_symbol.dart#L5).

**Comment by ThinkingFrog** [comment]
Нужно будет завести задачу на рефакторинг, на неё уже как минимум пара пунктов есть. Вопрос к @derkanw насколько это умещается в наши планы и на какой спринт лучше уложить

**Comment by derkanw** [comment]
> Нужно будет завести задачу на рефакторинг, на неё уже как минимум пара пунктов есть. Вопрос к @derkanw насколько это умещается в наши планы и на какой спринт лучше уложить

Хорошо, взяла на заметку. Обсудим вопрос о времени на планировании спринта. Думаю, если с разделом практики на первый взгляд проблем не будет, то можно попробовать и в следующий спринт поработать над рефакторингом.

**Comment by ThinkingFrog** [comment]
Было сделано в качестве отдельной задачи рефакторинга. Думаю, можно тоже закрывать
