### ISSUE TITLE
Enums

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learnbraille_ios#51]
Вы используете строчки в качестве перечислений. Таким образом, местами код написан по-русски. И в принципе это плохая практика за пределами JS. В дарте есть перечисления `enum`, лучше их использовать вместо `static final String groupName = "Знаки препинания";`. В андроиде мы все группы и экзотические символы ![записываем](https://github.com/braille-systems/learn-braille/blob/8033a3ded95f0524da5522f735e84b9eb1438a72/app/src/main/java/com/github/braillesystems/learnbraille/res/Materials.kt#L119) в енумах, а для не совсем экзотических символов, ![указываем](https://github.com/braille-systems/learn-braille/blob/8033a3ded95f0524da5522f735e84b9eb1438a72/app/src/main/java/com/github/braillesystems/learnbraille/res/Materials.kt#L136) юникодные диапазоны, когда задаём.

**Comment by ThinkingFrog** [comment]
@pikabol88 @OvechkinDanil @Oleg595 есть какие-то видимые ограничения, которые нам мешают это зарефакторить, или можно взять как задачу на следующий спринт?

**Comment by OvechkinDanil** [comment]
Лучше взять эту задачу на следующий спринт

**Comment by pikabol88** [comment]
Да, возьмем задачу на следующий спринт
Там уже точно есть то, что нуждается в рефакторинге

**Comment by OvechkinDanil** [comment]
Добавлены в PR #65
