### ISSUE TITLE
StructSymbol

### ISSUE THREAD

**Issue by winter-yuki** [braille-systems/learnbraille_ios#52]
В брайлеском шеститочии точки называются Dots, а не Points.

Мне вид `StructSymbol` кажется неудачным.
1. Класс не является иммутабельным.
2. Его наследники не являются финальными.
3. Класс выставляет необоснованно длинный контракт:
   1. Список должен быть определённой длины.
   2. Нумерация точек с такого индекса, а не с другого.
   3. Точки в списке не должны повторяться, ибо это странно.
   4. Номера точек должны быть в заданном диапазоне.

Точек у нас всегда 6, проще ![руками](https://github.com/braille-systems/learn-braille/blob/8033a3ded95f0524da5522f735e84b9eb1438a72/app/src/main/java/com/github/braillesystems/learnbraille/data/entities/BrailleDots.kt#L25) перечислить все шесть точек и ![предоставить](https://github.com/braille-systems/learn-braille/blob/8033a3ded95f0524da5522f735e84b9eb1438a72/app/src/main/java/com/github/braillesystems/learnbraille/data/entities/BrailleDots.kt#L56) методы линеаризации.

И соответственно вопросы к #39.

**Comment by ThinkingFrog** [comment]
Вроде это было исправлено в рамках 107 задачи. @Oleg595 подтверди, пожалуйста, мои слова. И сюда ещё можно #56 линкануть, это ветка под BRAILLE-107 задачу

**Comment by winter-yuki** [comment]
Было бы здорово синхронизировать терминологию в коде с тем, что уже ![было](https://github.com/braille-systems/learn-braille/tree/master/app/src/main/java/com/github/braillesystems/learnbraille/data/entities). Где чары, где символы и прочее.

**Comment by Oleg595** [comment]
Да, я исправил все пункты, за исключением 2 - ого, так как язык не предоставляет такой возможности. Решением данной проблемы является private - конструктор, но нужен ли он?

**Comment by ThinkingFrog** [comment]
Думаю, можно закрывать
